sudo: false
language: ruby
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
rvm:
    - 2.0
    - 2.1
install:
    - make setup
script:
    - make
    - bundle exec htmlproof --href-ignore "#" ./_site
